/*
  privacyIDEA Authenticator

  Authors: Nils Behlen <nils.behlen@netknights.it>

  Copyright (c) 2017-2019 NetKnights GmbH

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

package it.netknights.piauthenticator;

public class AppConstants {

    static final String APP_TITLE = " privacyIDEA Authenticator";
    static final String PACKAGE_NAME = "it.netknights.piauthenticator";
    static final String TAG = "PI-Authenticator";

    static final int INTENT_ADD_TOKEN_MANUALLY = 101;
    static final int INTENT_ABOUT = 102;
    static final int PERMISSIONS_REQUEST_CAMERA = 103;

    static final String CRYPT_ALGORITHM = "AES/GCM/NoPadding";
    static final String KEY_WRAP_ALGORITHM = "RSA/ECB/PKCS1Padding";
    static final int KEY_LENGTH = 16;
    static final int IV_LENGTH = 12;

    // ----- FILE NAMES -----
    static final String DATAFILE = "data.dat";
    static final String KEYFILE = "key.key";
    static final String PUBKEYFILE = "pubkey.key";
    static final String FB_CONFIG_FILE = "fbconf.dat";
    // -----------------------

    static final String DIGITS = "digits";
    static final String PERIOD = "period";
    static final String ALGORITHM = "algorithm";
    static final String ISSUER = "issuer";
    static final String SECRET = "secret";
    static final String TYPE = "type";
    static final String LABEL = "label";
    static final String COUNTER = "counter";
    static final String TOTP = "totp";
    static final String HOTP = "hotp";
    static final String TAPTOSHOW = "taptoshow";
    static final String PIN = "pin";
    static final String WITHPIN = "withpin";
    static final String TWOSTEP_SALT = "2step_salt";                // Size of the random bytes generated by the smartphone, which are used as salt for PBKDF2
    static final String TWOSTEP_DIFFICULTY = "2step_difficulty";    // PBKDF2 iterations
    static final String TWOSTEP_OUTPUT = "2step_output";            // size of the key generated by PBKDF2
    static final String PROPERTY_PROGRESS = "progress";
    static final String PERSISTENT = "persistent";

    static final String SHA1 = "SHA1";
    static final String SHA256 = "SHA256";
    static final String SHA512 = "SHA512";
    static final String HMACSHA1 = "HmacSHA1";
    static final String HMACSHA256 = "HmacSHA256";
    static final String HMACSHA512 = "HmacSHA512";

    static final String PERIOD_30_STR = "30s";
    static final String PERIOD_60_STR = "60s";
    static final int PERIOD_30 = 30;
    static final int PERIOD_60 = 60;

    static final String DIGITS_6_STR = "6";
    static final String DIGITS_8_STR = "8";


    // ----- Stuff for push -----
    // Attribute names
    static final String PUSH = "pipush";
    static final String URL = "url";
    static final String TTL = "ttl";
    static final String PROJECT_ID = "projectid";
    static final String APP_ID = "appid";
    static final String API_KEY = "apikey";
    static final String PROJECT_NUMBER = "projectnumber";
    static final String FB_TOKEN = "fbtoken";
    static final String ENROLLMENT_CRED = "enrollment_credential";

    // TODO
    static final String TITLE = "title";
    static final String NONCE = "nonce";
    static final String SIGNATURE = "signature";
    static final String SERIAL = "serial";
    static final String QUESTION = "question";
    static final String ROLLOUT_FINISHED = "rollout_finished";
    static final String ROLLOUT_EXPIRATION = "rollout_expiration";
    static final String PUSH_VERSION = "v";
    static final String SSL_VERIFY = "sslverify";
    static final String PUBKEY = "pubkey";
    static final String NOTIFICATION_ID = "notificationID";

    static final String RESPONSE_DETAIL = "detail";
    static final String RESPONSE_PUBLIC_KEY = "public_key";
    static final String RESPONSE_RESULT = "result";
    static final String RESPONSE_VALUE = "value";

    // Constants
    static final int READ_TIMEOUT = 10000;
    static final int CONNECT_TIMEOUT = 15000;

    static final String NOTIFICATION_CHANNEL_ID = "privacyIDEAPush";

    // Status codes
    static final int PRO_STATUS_STEP_1 = 1001;
    static final int PRO_STATUS_STEP_2 = 1002;
    static final int PRO_STATUS_STEP_3 = 1003;
    static final int PRO_STATUS_DONE = 1004;
    static final int PRO_STATUS_KEY_RECEIVED = 1005;
    static final int PRO_STATUS_REGISTRATION_TIME_EXPIRED = 1010;
    static final int PRO_STATUS_RESPONSE_NO_KEY = 1011;

    static final int PRO_STATUS_BAD_BASE64 = 1013;
    static final int PRO_STATUS_MALFORMED_JSON = 1015;
    static final int PRO_STATUS_RESPONSE_NOT_OK = 1016;

    static final int PA_INVALID_SIGNATURE = 2001;
    static final int PA_SIGNING_FAILURE = 2002;
    static final int PA_AUTHENTICATION_FINISHED = 2003;

    static final int STATUS_INIT_FIREBASE = 3101;
    static final int STATUS_INIT_FIREBASE_DONE = 3102;
    static final int STATUS_TWO_STEP_ROLLOUT = 3103;
    static final int STATUS_TWO_STEP_ROLLOUT_DONE = 3104;
    static final int STATUS_STANDARD_ROLLOUT_DONE = 3105;

    static final int STATUS_ENDPOINT_SENDING_COMPLETE = 4001;
    static final int STATUS_ENDPOINT_UNKNOWN_HOST = 4002;
    static final int STATUS_ENDPOINT_MALFORMED_URL = 4003;
    static final int STATUS_ENDPOINT_RESPONSE_RECEIVED = 4004;
    static final int STATUS_ENDPOINT_ERROR = 4005;
    static final int STATUS_ENDPOINT_SSL_ERROR = 4006;
}
